# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ketabkhor', '0005_auto_20170108_1215'),
        ('accounts', '0002_auto_20170108_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketabkhor.Book')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
