# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170108_1427'),
        ('books', '0002_auto_20170108_2154'),
        ('profiles', '0002_auto_20170108_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingbagBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
