# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_shoppingbagbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbagbook',
            name='book_count',
            field=models.IntegerField(default=1),
        ),
    ]
