# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_shoppingbagbook_book_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbagbook',
            old_name='user',
            new_name='user_profile',
        ),
    ]
