# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170108_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbagbook',
            old_name='user_profile',
            new_name='user',
        ),
    ]
