# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170108_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=256)),
                ('phone_number', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
    ]
