# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookreview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='title',
        ),
    ]
