# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170118_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
