# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0001_initial'),
        ('accounts', '0008_vendor'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingbagVendor',
            fields=[
                ('shoppingbagaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buying.ShoppingbagAddress')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor')),
            ],
            bases=('buying.shoppingbagaddress',),
        ),
    ]
