# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=127)),
                ('author', models.CharField(max_length=63)),
                ('translator', models.CharField(default='', max_length=63, null=True)),
                ('description', models.CharField(max_length=511)),
                ('page_count', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=127)),
                ('price', models.IntegerField(default=0)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='static/site-media/photos/books/')),
            ],
        ),
    ]
