# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('author', models.CharField(max_length=63)),
                ('translator', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=511)),
                ('page_count', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=127)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=511)),
                ('phone_number', models.IntegerField(default=0)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
    ]
