# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAdmin',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.IntegerField(default=0)),
                ('password_hash', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63)),
                ('context', models.CharField(max_length=511)),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('context', models.CharField(max_length=2047)),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('author', models.CharField(max_length=63)),
                ('context', models.CharField(max_length=511)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgram',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('current_page', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63)),
                ('context', models.CharField(max_length=511)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.IntegerField(default=0)),
                ('user_type', models.IntegerField(default=1)),
                ('password_hash', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=511)),
                ('phone_number', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('password_hash', models.CharField(max_length=511)),
            ],
        ),
    ]
