# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0002_blogadmin_blogcomment_blogpost_bookreview_readingprogram_supportticket_user_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=511)),
                ('phone_number', models.IntegerField(default=0)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
