# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0002_auto_20170106_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/site-media/photos/profiles/matthew.png', null=True, upload_to='static/site-media/photos/profiles/'),
        ),
    ]
