# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0003_auto_20161228_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ketabkhor.Address'),
        ),
    ]
