# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0005_auto_20170108_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
