# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170108_2028'),
        ('ketabkhor', '0006_auto_20170108_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
