# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ketabkhor', '0007_auto_20170108_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
